USE [argus] 
GO
/****** Object:  Table [dbo].[CONSULTAEXAMEFISICO]      ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONSULTAEXAMEFISICO](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[CODIGO_CONSULTA] [int] NOT NULL,
	[CODIGO_EXAMEFIS] [int] NOT NULL,
 CONSTRAINT [PK_CONSULTAEXAMEFISICO] PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CLASSIFICACAOECONOMICA]      ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CLASSIFICACAOECONOMICA](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](30) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[DIAGNOSTICO]      ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DIAGNOSTICO](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[ATIVO] [bit] NOT NULL,
	[NOME] [varchar](60) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[COR]      ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[COR](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[ATIVO] [bit] NOT NULL,
	[NOME] [varchar](60) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[CONSULTASTATUS]      ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CONSULTASTATUS](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[ATIVO] [bit] NOT NULL,
	[NOME] [varchar](60) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[ESPECIE]      ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ESPECIE](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[ATIVO] [bit] NOT NULL,
	[NOME] [varchar](60) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[ESTADO]      ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ESTADO](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[ATIVO] [bit] NOT NULL,
	[UF] [char](2) NOT NULL,
	[NOME] [varchar](60) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[EXAMEFISICO]      ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[EXAMEFISICO](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](60) NOT NULL,
	[ATIVO] [bit] NOT NULL,
 CONSTRAINT [PK__EXAMEFIS__CC87E127540C7B00] PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PRODUTOSERVICO]    Script Date: 11/24/2011 20:54:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PRODUTOSERVICO](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[ATIVO] [bit] NOT NULL,
	[NOME] [varchar](60) NOT NULL,
	[TIPO] [char](1) NOT NULL,
	[DT_VALIDADE] [date] NULL,
 CONSTRAINT [PK__PRODUTOS__CC87E1271B0907CE] PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PROCEDIMENTO]    Script Date: 11/24/2011 20:54:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PROCEDIMENTO](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](60) NOT NULL,
	[DESCRICAO] [text] NOT NULL,
 CONSTRAINT [PK__PROCEDIM__CC87E1272FCF1A8A] PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PORTE]    Script Date: 11/24/2011 20:54:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PORTE](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](60) NOT NULL,
 CONSTRAINT [PK_PORTE] PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PERFIL]    Script Date: 11/24/2011 20:54:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PERFIL](
	[CODIGO] [int] NOT NULL,
	[NOME] [varchar](60) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PELAGEM]    Script Date: 11/24/2011 20:54:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PELAGEM](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[ATIVO] [bit] NOT NULL,
	[NOME] [varchar](60) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[MOTIVOBAIXA]      ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MOTIVOBAIXA](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[ATIVO] [bit] NOT NULL,
	[NOME] [varchar](60) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TIPOVISITA]    Script Date: 11/24/2011 20:54:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TIPOVISITA](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[ATIVO] [bit] NOT NULL,
	[NOME] [varchar](60) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TEMPERAMENTO]    Script Date: 11/24/2011 20:54:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TEMPERAMENTO](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[ATIVO] [bit] NOT NULL,
	[NOME] [varchar](60) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[RACA]    Script Date: 11/24/2011 20:54:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[RACA](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[ATIVO] [bit] NOT NULL,
	[CODIGO_ESPECIE] [int] NOT NULL,
	[NOME] [varchar](60) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[EXAMEFISICOITEM]      ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[EXAMEFISICOITEM](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[CODIGO_EXAMEFIS] [int] NOT NULL,
	[CODIGO_ITEM] [int] NOT NULL,
	[NOME] [varchar](60) NULL,
 CONSTRAINT [PK_EXAMEFISICOITEM] PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UN_EXAITEM] UNIQUE NONCLUSTERED 
(
	[CODIGO_EXAMEFIS] ASC,
	[CODIGO_ITEM] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[EXAME]      ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[EXAME](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[ATIVO] [bit] NOT NULL,
	[NOME] [varchar](60) NOT NULL,
	[DESCRICAO] [varchar](512) NULL,
	[CODIGO_PRODSERV] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[ESPECIEDOENCA]      ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ESPECIEDOENCA](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[CODIGO_ESPECIE] [int] NOT NULL,
	[ATIVO] [bit] NOT NULL,
	[NOME] [varchar](60) NOT NULL,
	[DESCRICAO] [text] NOT NULL,
 CONSTRAINT [PK_ESPECIE_DOENCA] PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[ESPECIECHECKUP]      ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ESPECIECHECKUP](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[CODIGO_ESPECIE] [int] NOT NULL,
	[ATIVO] [bit] NOT NULL,
	[DE] [int] NOT NULL,
	[ATE] [int] NOT NULL,
	[DESCRICAO] [text] NOT NULL,
 CONSTRAINT [PK__ESPECIE__CC87E1274AB81AF0] PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CIDADE]      ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CIDADE](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[CODIGO_ESTADO] [int] NOT NULL,
	[ATIVO] [bit] NOT NULL,
	[NOME] [varchar](60) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[ANIMAL]      ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ANIMAL](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[CODIGO_CLIENTE] [int] NOT NULL,
	[CODIGO_VETERINARIO] [int] NULL,
	[CODIGO_TEMPERAMENTO] [int] NULL,
	[CODIGO_PELAGEM] [int] NULL,
	[CODIGO_COR] [int] NULL,
	[CODIGO_RACA] [int] NULL,
	[ATIVO] [bit] NOT NULL,
	[NOME] [varchar](60) NOT NULL,
	[CODIGO_PORTE] [int] NULL,
	[DT_NASCIMENTO] [date] NULL,
	[DT_CADASTRO] [date] NOT NULL,
	[SEXO] [char](1) NULL,
	[NCHIP] [int] NULL,
	[NCCI] [int] NULL,
	[PEDIGREE] [bit] NULL,
	[NPEDIGREE] [bit] NULL,
	[OBSERVACAO] [varchar](2048) NULL,
	[CODIGO_MOTBAIXA] [int] NULL,
	[TP_SANGUINEO] [varchar](3) NULL,
	[CODIGO_ESPECIE] [int] NOT NULL,
	[TP_DIETA] [int] NULL,
	[CAMINHO_FOTO] [varchar](512) NULL,
 CONSTRAINT [PK__ANIMAL__CC87E127403A8C7D] PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[MEDICINAPREV]      ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MEDICINAPREV](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[CODIGO_RACA] [int] NOT NULL,
	[DESCRICAO] [varchar](2048) NOT NULL,
 CONSTRAINT [PK__MEDICINA__CC87E127625A9A57] PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[EXAMEREFERENCIA]      ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[EXAMEREFERENCIA](
	[CODIGO_EXAME] [int] NOT NULL,
	[CODIGO_ITEM] [int] IDENTITY(1,1) NOT NULL,
	[DESCRICAO] [varchar](60) NOT NULL,
	[UNIDADES] [varchar](10) NULL,
	[DE] [int] NULL,
	[ATE] [int] NULL,
 CONSTRAINT [PK_EXAMEREFERENCIA] PRIMARY KEY CLUSTERED 
(
	[CODIGO_EXAME] ASC,
	[CODIGO_ITEM] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PESSOA]    Script Date: 11/24/2011 20:54:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PESSOA](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[CODIGO_CIDADE] [int] NULL,
	[ATIVO] [bit] NOT NULL,
	[NOME] [varchar](60) NOT NULL,
	[DT_NASCIMENTO] [date] NULL,
	[DT_CADASTRO] [date] NOT NULL,
	[ENDERECO] [varchar](120) NULL,
	[ENVIAR_EMAIL] [bit] NOT NULL,
	[EMAIL] [varchar](60) NULL,
	[OBSERVACAO] [text] NULL,
 CONSTRAINT [PK__PESSOA__CC87E1274E88ABD4] PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[CONSULTAEXAMEFISICOITEM]      ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CONSULTAEXAMEFISICOITEM](
	[CODIGO_CONEXAFIS] [int] NOT NULL,
	[CODIGO_EXAMEFISITEM] [int] NOT NULL,
	[RESULTADO] [varchar](60) NULL,
 CONSTRAINT [PK_CONSULTAEXAMEFISICOITEM_1] PRIMARY KEY CLUSTERED 
(
	[CODIGO_CONEXAFIS] ASC,
	[CODIGO_EXAMEFISITEM] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[VETERINARIO]    Script Date: 11/24/2011 20:54:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[VETERINARIO](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[CODIGO_PESSOA] [int] NOT NULL,
	[CRMV] [varchar](11) NOT NULL,
 CONSTRAINT [PK_VETERINARIO] PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[USUARIO]    Script Date: 11/24/2011 20:54:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[USUARIO](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[CODIGO_PESSOA] [int] NOT NULL,
	[LOGIN] [varchar](30) NOT NULL,
	[SENHA] [varchar](30) NOT NULL,
	[CODIGO_PERFIL] [int] NOT NULL,
 CONSTRAINT [PK_USUARIO] PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PESSOATELEFONE]    Script Date: 11/24/2011 20:54:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PESSOATELEFONE](
	[CODIGO_PESSOA] [int] NOT NULL,
	[TELEFONE] [varchar](10) NOT NULL,
 CONSTRAINT [PK_PESSOATELEFONE] PRIMARY KEY CLUSTERED 
(
	[CODIGO_PESSOA] ASC,
	[TELEFONE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[ENVIOEMAIL]      ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ENVIOEMAIL](
	[CODIGO_ANIMAL] [int] NOT NULL,
	[CODIGO_ESPECIECHECKUP] [int] NOT NULL,
	[DATA_CRIACAO] [date] NOT NULL,
	[DATA_ENVIO] [date] NOT NULL,
	[CONTEUDO_EMAIL] [varchar](1024) NOT NULL,
	[STATUS] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO_ANIMAL] ASC,
	[CODIGO_ESPECIECHECKUP] ASC,
	[DATA_CRIACAO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[ANIMALIMAGEM]      ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ANIMALIMAGEM](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[CODIGO_ANIMAL] [int] NOT NULL,
	[DTHR_ATUALIZACAO] [datetime] NOT NULL,
	[NOME_FOTO] [varchar](512) NOT NULL,
	[OBSERVACAO] [varchar](2048) NULL,
 CONSTRAINT [PK__ANIMALIM__CC87E12747DBAE45] PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[CLIENTE]      ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CLIENTE](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[CODIGO_PESSOA] [int] NOT NULL,
	[CODIGO_TEMPERAMENTO] [int] NULL,
	[NFILHOS] [int] NULL,
	[NANIMAIS] [int] NULL,
 CONSTRAINT [PK_CLIENTE] PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONSULTA]      ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONSULTA](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[CODIGO_CLIENTE] [int] NOT NULL,
	[CODIGO_ANIMAL] [int] NOT NULL,
	[CODIGO_VETERINARIO] [int] NOT NULL,
	[CODIGOTP_VISITA] [int] NOT NULL,
	[DTHR_CONSULTA] [datetime] NOT NULL,
	[ANAMNESE] [text] NOT NULL,
	[DIAGNOSTICO] [text] NULL,
	[TRATAMENTO] [text] NULL,
	[DTHR_STATUS] [datetime] NOT NULL,
	[CODIGO_STATUS] [int] NOT NULL,
 CONSTRAINT [PK__CONSULTA__CC87E1276EF57B66] PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONSULTAEXAME]      ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CONSULTAEXAME](
	[CODIGO_CONSULTA] [int] NOT NULL,
	[CODIGO_EXAME] [int] NOT NULL,
	[DTHR_SOLICITACAO] [datetime] NOT NULL,
	[DTHR_RESULTADO] [datetime] NULL,
	[OBSERVACAO] [varchar](512) NULL,
 CONSTRAINT [PK_CONSULTAEXAME] PRIMARY KEY CLUSTERED 
(
	[CODIGO_CONSULTA] ASC,
	[CODIGO_EXAME] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[CONSULTAPRODSERV]      ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONSULTAPRODSERV](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[CODIGO_CONSULTA] [int] NOT NULL,
	[CODIGO_PRODSERV] [int] NOT NULL,
 CONSTRAINT [PK_CONSULTAPRODSERV] PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONSULTAEXAMERESULTADO]      ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CONSULTAEXAMERESULTADO](
	[CODIGO_CONSULTA] [int] NOT NULL,
	[CODIGO_EXAME] [int] NOT NULL,
	[CODIGO_ITEM] [int] NOT NULL,
	[RESULTADO] [varchar](10) NOT NULL,
 CONSTRAINT [PK_CONSULTAEXAMERESULTADO] PRIMARY KEY CLUSTERED 
(
	[CODIGO_CONSULTA] ASC,
	[CODIGO_EXAME] ASC,
	[CODIGO_ITEM] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Default [DF__ANIMAL__ATIVO__0519C6AF]      ******/
ALTER TABLE [dbo].[ANIMAL] ADD  CONSTRAINT [DF__ANIMAL__ATIVO__0519C6AF]  DEFAULT ((1)) FOR [ATIVO]
GO
/****** Object:  Default [DF__ANIMAL__DT_CADA__060DEAE8]      ******/
ALTER TABLE [dbo].[ANIMAL] ADD  CONSTRAINT [DF__ANIMAL__DT_CADA__060DEAE8]  DEFAULT (getdate()) FOR [DT_CADASTRO]
GO
/****** Object:  Default [DF_ANIMAL_PEDIGREE]      ******/
ALTER TABLE [dbo].[ANIMAL] ADD  CONSTRAINT [DF_ANIMAL_PEDIGREE]  DEFAULT ((1)) FOR [PEDIGREE]
GO
/****** Object:  Default [DF__ANIMALIMA__DTHR___5BE2A6F2]      ******/
ALTER TABLE [dbo].[ANIMALIMAGEM] ADD  CONSTRAINT [DF__ANIMALIMA__DTHR___5BE2A6F2]  DEFAULT (getdate()) FOR [DTHR_ATUALIZACAO]
GO
/****** Object:  Default [DF__CIDADE__ATIVO__656C112C]      ******/
ALTER TABLE [dbo].[CIDADE] ADD  DEFAULT ((1)) FOR [ATIVO]
GO
/****** Object:  Default [DF__CONSULTA__DTHR___02FC7413]      ******/
ALTER TABLE [dbo].[CONSULTA] ADD  CONSTRAINT [DF__CONSULTA__DTHR___02FC7413]  DEFAULT (getdate()) FOR [DTHR_CONSULTA]
GO
/****** Object:  Default [DF__CONSULTA__STATU__03F0984C]      ******/
ALTER TABLE [dbo].[CONSULTA] ADD  CONSTRAINT [DF__CONSULTA__STATU__03F0984C]  DEFAULT ((1)) FOR [CODIGO_STATUS]
GO
/****** Object:  Default [DF__CONSULTAS__ATIVO__68487DD7]      ******/
ALTER TABLE [dbo].[CONSULTASTATUS] ADD  DEFAULT ((1)) FOR [ATIVO]
GO
/****** Object:  Default [DF__COR__ATIVO__693CA210]      ******/
ALTER TABLE [dbo].[COR] ADD  DEFAULT ((1)) FOR [ATIVO]
GO
/****** Object:  Default [DF__ENVIOEMAI__DATA___6A30C649]      ******/
ALTER TABLE [dbo].[ENVIOEMAIL] ADD  DEFAULT (getdate()) FOR [DATA_CRIACAO]
GO
/****** Object:  Default [DF__ENVIOEMAI__STATU__6B24EA82]      ******/
ALTER TABLE [dbo].[ENVIOEMAIL] ADD  DEFAULT ('P') FOR [STATUS]
GO
/****** Object:  Default [DF__ESPECIE__ATIVO__6C190EBB]      ******/
ALTER TABLE [dbo].[ESPECIE] ADD  DEFAULT ((1)) FOR [ATIVO]
GO
/****** Object:  Default [DF__ESPECIE___ATIVO__09A971A2]      ******/
ALTER TABLE [dbo].[ESPECIECHECKUP] ADD  CONSTRAINT [DF__ESPECIE___ATIVO__09A971A2]  DEFAULT ((1)) FOR [ATIVO]
GO
/****** Object:  Default [DF__ESPECIE___ATIVO__0A9D95DB]      ******/
ALTER TABLE [dbo].[ESPECIEDOENCA] ADD  CONSTRAINT [DF__ESPECIE___ATIVO__0A9D95DB]  DEFAULT ((1)) FOR [ATIVO]
GO
/****** Object:  Default [DF__ESTADO__ATIVO__6EF57B66]      ******/
ALTER TABLE [dbo].[ESTADO] ADD  DEFAULT ((1)) FOR [ATIVO]
GO
/****** Object:  Default [DF__EXAME__ATIVO__6FE99F9F]      ******/
ALTER TABLE [dbo].[EXAME] ADD  DEFAULT ((1)) FOR [ATIVO]
GO
/****** Object:  Default [DF__EXAMEFISI__ATIVO__55F4C372]      ******/
ALTER TABLE [dbo].[EXAMEFISICO] ADD  CONSTRAINT [DF__EXAMEFISI__ATIVO__55F4C372]  DEFAULT ((1)) FOR [ATIVO]
GO
/****** Object:  Default [DF__MOTIVOBAI__ATIVO__71D1E811]      ******/
ALTER TABLE [dbo].[MOTIVOBAIXA] ADD  DEFAULT ((1)) FOR [ATIVO]
GO
/****** Object:  Default [DF__PELAGEM__ATIVO__72C60C4A]    Script Date: 11/24/2011 20:54:16 ******/
ALTER TABLE [dbo].[PELAGEM] ADD  DEFAULT ((1)) FOR [ATIVO]
GO
/****** Object:  Default [DF__PESSOA__ATIVO__10566F31]    Script Date: 11/24/2011 20:54:16 ******/
ALTER TABLE [dbo].[PESSOA] ADD  CONSTRAINT [DF__PESSOA__ATIVO__10566F31]  DEFAULT ((1)) FOR [ATIVO]
GO
/****** Object:  Default [DF__PESSOA__DT_CADA__114A936A]    Script Date: 11/24/2011 20:54:16 ******/
ALTER TABLE [dbo].[PESSOA] ADD  CONSTRAINT [DF__PESSOA__DT_CADA__114A936A]  DEFAULT (getdate()) FOR [DT_CADASTRO]
GO
/****** Object:  Default [DF_PESSOA_ENVIAR_EMAIL]    Script Date: 11/24/2011 20:54:16 ******/
ALTER TABLE [dbo].[PESSOA] ADD  CONSTRAINT [DF_PESSOA_ENVIAR_EMAIL]  DEFAULT ((1)) FOR [ENVIAR_EMAIL]
GO
/****** Object:  Default [DF__PRODUTOSE__ATIVO__778AC167]    Script Date: 11/24/2011 20:54:16 ******/
ALTER TABLE [dbo].[PRODUTOSERVICO] ADD  CONSTRAINT [DF__PRODUTOSE__ATIVO__778AC167]  DEFAULT ((1)) FOR [ATIVO]
GO
/****** Object:  Default [DF_PRODUTOSERVICO_TIPO]    Script Date: 11/24/2011 20:54:16 ******/
ALTER TABLE [dbo].[PRODUTOSERVICO] ADD  CONSTRAINT [DF_PRODUTOSERVICO_TIPO]  DEFAULT ('S') FOR [TIPO]
GO
/****** Object:  Default [DF__RACA__ATIVO__787EE5A0]    Script Date: 11/24/2011 20:54:16 ******/
ALTER TABLE [dbo].[RACA] ADD  DEFAULT ((1)) FOR [ATIVO]
GO
/****** Object:  Default [DF__TEMPERAME__ATIVO__797309D9]    Script Date: 11/24/2011 20:54:16 ******/
ALTER TABLE [dbo].[TEMPERAMENTO] ADD  DEFAULT ((1)) FOR [ATIVO]
GO
/****** Object:  Default [DF__TIPOVISIT__ATIVO__7A672E12]    Script Date: 11/24/2011 20:54:16 ******/
ALTER TABLE [dbo].[TIPOVISITA] ADD  DEFAULT ((1)) FOR [ATIVO]
GO
/****** Object:  ForeignKey [FK_ANI_CODIGO_COR]      ******/
ALTER TABLE [dbo].[ANIMAL]  WITH CHECK ADD  CONSTRAINT [FK_ANI_CODIGO_COR] FOREIGN KEY([CODIGO_COR])
REFERENCES [dbo].[COR] ([CODIGO])
GO
ALTER TABLE [dbo].[ANIMAL] CHECK CONSTRAINT [FK_ANI_CODIGO_COR]
GO
/****** Object:  ForeignKey [FK_ANI_CODIGO_MOTBAIXA]      ******/
ALTER TABLE [dbo].[ANIMAL]  WITH CHECK ADD  CONSTRAINT [FK_ANI_CODIGO_MOTBAIXA] FOREIGN KEY([CODIGO_MOTBAIXA])
REFERENCES [dbo].[MOTIVOBAIXA] ([CODIGO])
GO
ALTER TABLE [dbo].[ANIMAL] CHECK CONSTRAINT [FK_ANI_CODIGO_MOTBAIXA]
GO
/****** Object:  ForeignKey [FK_ANI_CODIGO_PELAGEM]      ******/
ALTER TABLE [dbo].[ANIMAL]  WITH CHECK ADD  CONSTRAINT [FK_ANI_CODIGO_PELAGEM] FOREIGN KEY([CODIGO_PELAGEM])
REFERENCES [dbo].[PELAGEM] ([CODIGO])
GO
ALTER TABLE [dbo].[ANIMAL] CHECK CONSTRAINT [FK_ANI_CODIGO_PELAGEM]
GO
/****** Object:  ForeignKey [FK_ANI_CODIGO_POR]      ******/
ALTER TABLE [dbo].[ANIMAL]  WITH CHECK ADD  CONSTRAINT [FK_ANI_CODIGO_POR] FOREIGN KEY([CODIGO_PORTE])
REFERENCES [dbo].[PORTE] ([CODIGO])
GO
ALTER TABLE [dbo].[ANIMAL] CHECK CONSTRAINT [FK_ANI_CODIGO_POR]
GO
/****** Object:  ForeignKey [FK_ANI_CODIGO_RACA]      ******/
ALTER TABLE [dbo].[ANIMAL]  WITH CHECK ADD  CONSTRAINT [FK_ANI_CODIGO_RACA] FOREIGN KEY([CODIGO_RACA])
REFERENCES [dbo].[RACA] ([CODIGO])
GO
ALTER TABLE [dbo].[ANIMAL] CHECK CONSTRAINT [FK_ANI_CODIGO_RACA]
GO
/****** Object:  ForeignKey [FK_ANI_CODIGO_TEMPERAMENTO]      ******/
ALTER TABLE [dbo].[ANIMAL]  WITH CHECK ADD  CONSTRAINT [FK_ANI_CODIGO_TEMPERAMENTO] FOREIGN KEY([CODIGO_TEMPERAMENTO])
REFERENCES [dbo].[TEMPERAMENTO] ([CODIGO])
GO
ALTER TABLE [dbo].[ANIMAL] CHECK CONSTRAINT [FK_ANI_CODIGO_TEMPERAMENTO]
GO
/****** Object:  ForeignKey [FK_ANIMAL_CODIGO_ESPECIE]      ******/
ALTER TABLE [dbo].[ANIMAL]  WITH CHECK ADD  CONSTRAINT [FK_ANIMAL_CODIGO_ESPECIE] FOREIGN KEY([CODIGO_ESPECIE])
REFERENCES [dbo].[ESPECIE] ([CODIGO])
GO
ALTER TABLE [dbo].[ANIMAL] CHECK CONSTRAINT [FK_ANIMAL_CODIGO_ESPECIE]
GO
/****** Object:  ForeignKey [FK_ANIIMA_CODIGO_ANIMAL]      ******/
ALTER TABLE [dbo].[ANIMALIMAGEM]  WITH CHECK ADD  CONSTRAINT [FK_ANIIMA_CODIGO_ANIMAL] FOREIGN KEY([CODIGO_ANIMAL])
REFERENCES [dbo].[ANIMAL] ([CODIGO])
GO
ALTER TABLE [dbo].[ANIMALIMAGEM] CHECK CONSTRAINT [FK_ANIIMA_CODIGO_ANIMAL]
GO
/****** Object:  ForeignKey [FK_CID_CODIGO_ESTADO]      ******/
ALTER TABLE [dbo].[CIDADE]  WITH CHECK ADD  CONSTRAINT [FK_CID_CODIGO_ESTADO] FOREIGN KEY([CODIGO_ESTADO])
REFERENCES [dbo].[ESTADO] ([CODIGO])
GO
ALTER TABLE [dbo].[CIDADE] CHECK CONSTRAINT [FK_CID_CODIGO_ESTADO]
GO
/****** Object:  ForeignKey [FK_CLI_CODIGO_PESSOA]      ******/
ALTER TABLE [dbo].[CLIENTE]  WITH CHECK ADD  CONSTRAINT [FK_CLI_CODIGO_PESSOA] FOREIGN KEY([CODIGO_PESSOA])
REFERENCES [dbo].[PESSOA] ([CODIGO])
GO
ALTER TABLE [dbo].[CLIENTE] CHECK CONSTRAINT [FK_CLI_CODIGO_PESSOA]
GO
/****** Object:  ForeignKey [FK_CLI_CODIGO_TEMP]      ******/
ALTER TABLE [dbo].[CLIENTE]  WITH CHECK ADD  CONSTRAINT [FK_CLI_CODIGO_TEMP] FOREIGN KEY([CODIGO_TEMPERAMENTO])
REFERENCES [dbo].[TEMPERAMENTO] ([CODIGO])
GO
ALTER TABLE [dbo].[CLIENTE] CHECK CONSTRAINT [FK_CLI_CODIGO_TEMP]
GO
/****** Object:  ForeignKey [FK__CONSULTA__CODIGO__22751F6C]      ******/
ALTER TABLE [dbo].[CONSULTA]  WITH CHECK ADD FOREIGN KEY([CODIGO_VETERINARIO])
REFERENCES [dbo].[VETERINARIO] ([CODIGO])
GO
/****** Object:  ForeignKey [FK_CON_CODIGO_ANIMAL]      ******/
ALTER TABLE [dbo].[CONSULTA]  WITH CHECK ADD  CONSTRAINT [FK_CON_CODIGO_ANIMAL] FOREIGN KEY([CODIGO_ANIMAL])
REFERENCES [dbo].[ANIMAL] ([CODIGO])
GO
ALTER TABLE [dbo].[CONSULTA] CHECK CONSTRAINT [FK_CON_CODIGO_ANIMAL]
GO
/****** Object:  ForeignKey [FK_CON_CODIGO_CLIENTE]      ******/
ALTER TABLE [dbo].[CONSULTA]  WITH CHECK ADD  CONSTRAINT [FK_CON_CODIGO_CLIENTE] FOREIGN KEY([CODIGO_CLIENTE])
REFERENCES [dbo].[CLIENTE] ([CODIGO])
GO
ALTER TABLE [dbo].[CONSULTA] CHECK CONSTRAINT [FK_CON_CODIGO_CLIENTE]
GO
/****** Object:  ForeignKey [FK_CON_CODIGOTP_VISITA]      ******/
ALTER TABLE [dbo].[CONSULTA]  WITH CHECK ADD  CONSTRAINT [FK_CON_CODIGOTP_VISITA] FOREIGN KEY([CODIGOTP_VISITA])
REFERENCES [dbo].[TIPOVISITA] ([CODIGO])
GO
ALTER TABLE [dbo].[CONSULTA] CHECK CONSTRAINT [FK_CON_CODIGOTP_VISITA]
GO
/****** Object:  ForeignKey [FK_CON_CODSTATUS_CONSULTASTATUS]      ******/
ALTER TABLE [dbo].[CONSULTA]  WITH CHECK ADD  CONSTRAINT [FK_CON_CODSTATUS_CONSULTASTATUS] FOREIGN KEY([CODIGO_STATUS])
REFERENCES [dbo].[CONSULTASTATUS] ([CODIGO])
GO
ALTER TABLE [dbo].[CONSULTA] CHECK CONSTRAINT [FK_CON_CODSTATUS_CONSULTASTATUS]
GO
/****** Object:  ForeignKey [FK_CONEXA_CODIGO_CONSULTA]      ******/
ALTER TABLE [dbo].[CONSULTAEXAME]  WITH CHECK ADD  CONSTRAINT [FK_CONEXA_CODIGO_CONSULTA] FOREIGN KEY([CODIGO_CONSULTA])
REFERENCES [dbo].[CONSULTA] ([CODIGO])
GO
ALTER TABLE [dbo].[CONSULTAEXAME] CHECK CONSTRAINT [FK_CONEXA_CODIGO_CONSULTA]
GO
/****** Object:  ForeignKey [FK_CONEXA_CODIGO_EXAME]      ******/
ALTER TABLE [dbo].[CONSULTAEXAME]  WITH CHECK ADD  CONSTRAINT [FK_CONEXA_CODIGO_EXAME] FOREIGN KEY([CODIGO_EXAME])
REFERENCES [dbo].[EXAME] ([CODIGO])
GO
ALTER TABLE [dbo].[CONSULTAEXAME] CHECK CONSTRAINT [FK_CONEXA_CODIGO_EXAME]
GO
/****** Object:  ForeignKey [FK_CONEXAFIS_COD]      ******/
ALTER TABLE [dbo].[CONSULTAEXAMEFISICOITEM]  WITH CHECK ADD  CONSTRAINT [FK_CONEXAFIS_COD] FOREIGN KEY([CODIGO_CONEXAFIS])
REFERENCES [dbo].[CONSULTAEXAMEFISICO] ([CODIGO])
GO
ALTER TABLE [dbo].[CONSULTAEXAMEFISICOITEM] CHECK CONSTRAINT [FK_CONEXAFIS_COD]
GO
/****** Object:  ForeignKey [FK_EXAFISITEM_COD]      ******/
ALTER TABLE [dbo].[CONSULTAEXAMEFISICOITEM]  WITH CHECK ADD  CONSTRAINT [FK_EXAFISITEM_COD] FOREIGN KEY([CODIGO_EXAMEFISITEM])
REFERENCES [dbo].[EXAMEFISICOITEM] ([CODIGO])
GO
ALTER TABLE [dbo].[CONSULTAEXAMEFISICOITEM] CHECK CONSTRAINT [FK_EXAFISITEM_COD]
GO
/****** Object:  ForeignKey [FK_CONEXARES_CODCON_CODEXA]      ******/
ALTER TABLE [dbo].[CONSULTAEXAMERESULTADO]  WITH CHECK ADD  CONSTRAINT [FK_CONEXARES_CODCON_CODEXA] FOREIGN KEY([CODIGO_CONSULTA], [CODIGO_EXAME])
REFERENCES [dbo].[CONSULTAEXAME] ([CODIGO_CONSULTA], [CODIGO_EXAME])
GO
ALTER TABLE [dbo].[CONSULTAEXAMERESULTADO] CHECK CONSTRAINT [FK_CONEXARES_CODCON_CODEXA]
GO
/****** Object:  ForeignKey [FK_CONPROSER_CODIGO_CONSULTA]      ******/
ALTER TABLE [dbo].[CONSULTAPRODSERV]  WITH CHECK ADD  CONSTRAINT [FK_CONPROSER_CODIGO_CONSULTA] FOREIGN KEY([CODIGO_CONSULTA])
REFERENCES [dbo].[CONSULTA] ([CODIGO])
GO
ALTER TABLE [dbo].[CONSULTAPRODSERV] CHECK CONSTRAINT [FK_CONPROSER_CODIGO_CONSULTA]
GO
/****** Object:  ForeignKey [FK_CONPROSER_CODIGO_PRODSERV]      ******/
ALTER TABLE [dbo].[CONSULTAPRODSERV]  WITH CHECK ADD  CONSTRAINT [FK_CONPROSER_CODIGO_PRODSERV] FOREIGN KEY([CODIGO_PRODSERV])
REFERENCES [dbo].[PRODUTOSERVICO] ([CODIGO])
GO
ALTER TABLE [dbo].[CONSULTAPRODSERV] CHECK CONSTRAINT [FK_CONPROSER_CODIGO_PRODSERV]
GO
/****** Object:  ForeignKey [FK_ENVEMAI_COD_ESP_CHECK]      ******/
ALTER TABLE [dbo].[ENVIOEMAIL]  WITH CHECK ADD  CONSTRAINT [FK_ENVEMAI_COD_ESP_CHECK] FOREIGN KEY([CODIGO_ESPECIECHECKUP])
REFERENCES [dbo].[ESPECIECHECKUP] ([CODIGO])
GO
ALTER TABLE [dbo].[ENVIOEMAIL] CHECK CONSTRAINT [FK_ENVEMAI_COD_ESP_CHECK]
GO
/****** Object:  ForeignKey [FK_ENVIOEMAIL_ANIMAL]      ******/
ALTER TABLE [dbo].[ENVIOEMAIL]  WITH CHECK ADD  CONSTRAINT [FK_ENVIOEMAIL_ANIMAL] FOREIGN KEY([CODIGO_ANIMAL])
REFERENCES [dbo].[ANIMAL] ([CODIGO])
GO
ALTER TABLE [dbo].[ENVIOEMAIL] CHECK CONSTRAINT [FK_ENVIOEMAIL_ANIMAL]
GO
/****** Object:  ForeignKey [FK_ESPCHECK_CODIGO_ESPECIE]      ******/
ALTER TABLE [dbo].[ESPECIECHECKUP]  WITH CHECK ADD  CONSTRAINT [FK_ESPCHECK_CODIGO_ESPECIE] FOREIGN KEY([CODIGO_ESPECIE])
REFERENCES [dbo].[ESPECIE] ([CODIGO])
GO
ALTER TABLE [dbo].[ESPECIECHECKUP] CHECK CONSTRAINT [FK_ESPCHECK_CODIGO_ESPECIE]
GO
/****** Object:  ForeignKey [FK_ESPDOE_CODIGO_ESPECIE]      ******/
ALTER TABLE [dbo].[ESPECIEDOENCA]  WITH CHECK ADD  CONSTRAINT [FK_ESPDOE_CODIGO_ESPECIE] FOREIGN KEY([CODIGO_ESPECIE])
REFERENCES [dbo].[ESPECIE] ([CODIGO])
GO
ALTER TABLE [dbo].[ESPECIEDOENCA] CHECK CONSTRAINT [FK_ESPDOE_CODIGO_ESPECIE]
GO
/****** Object:  ForeignKey [FK_EXA_CODIGO_PRODSERV]      ******/
ALTER TABLE [dbo].[EXAME]  WITH CHECK ADD  CONSTRAINT [FK_EXA_CODIGO_PRODSERV] FOREIGN KEY([CODIGO_PRODSERV])
REFERENCES [dbo].[PRODUTOSERVICO] ([CODIGO])
GO
ALTER TABLE [dbo].[EXAME] CHECK CONSTRAINT [FK_EXA_CODIGO_PRODSERV]
GO
/****** Object:  ForeignKey [FK_COD_EXAFIS]      ******/
ALTER TABLE [dbo].[EXAMEFISICOITEM]  WITH CHECK ADD  CONSTRAINT [FK_COD_EXAFIS] FOREIGN KEY([CODIGO_EXAMEFIS])
REFERENCES [dbo].[EXAMEFISICO] ([CODIGO])
GO
ALTER TABLE [dbo].[EXAMEFISICOITEM] CHECK CONSTRAINT [FK_COD_EXAFIS]
GO
/****** Object:  ForeignKey [FK_EXAREF_CODIGO_EXAME]      ******/
ALTER TABLE [dbo].[EXAMEREFERENCIA]  WITH CHECK ADD  CONSTRAINT [FK_EXAREF_CODIGO_EXAME] FOREIGN KEY([CODIGO_EXAME])
REFERENCES [dbo].[EXAME] ([CODIGO])
GO
ALTER TABLE [dbo].[EXAMEREFERENCIA] CHECK CONSTRAINT [FK_EXAREF_CODIGO_EXAME]
GO
/****** Object:  ForeignKey [FK_MEDPREV_CODIGO_RACA]      ******/
ALTER TABLE [dbo].[MEDICINAPREV]  WITH CHECK ADD  CONSTRAINT [FK_MEDPREV_CODIGO_RACA] FOREIGN KEY([CODIGO_RACA])
REFERENCES [dbo].[RACA] ([CODIGO])
GO
ALTER TABLE [dbo].[MEDICINAPREV] CHECK CONSTRAINT [FK_MEDPREV_CODIGO_RACA]
GO
/****** Object:  ForeignKey [FK_PES_CODIGO_CIDADE]    Script Date: 11/24/2011 20:54:16 ******/
ALTER TABLE [dbo].[PESSOA]  WITH CHECK ADD  CONSTRAINT [FK_PES_CODIGO_CIDADE] FOREIGN KEY([CODIGO_CIDADE])
REFERENCES [dbo].[CIDADE] ([CODIGO])
GO
ALTER TABLE [dbo].[PESSOA] CHECK CONSTRAINT [FK_PES_CODIGO_CIDADE]
GO
/****** Object:  ForeignKey [FK_PESTEL_CODIGO_PESSOA]    Script Date: 11/24/2011 20:54:16 ******/
ALTER TABLE [dbo].[PESSOATELEFONE]  WITH CHECK ADD  CONSTRAINT [FK_PESTEL_CODIGO_PESSOA] FOREIGN KEY([CODIGO_PESSOA])
REFERENCES [dbo].[PESSOA] ([CODIGO])
GO
ALTER TABLE [dbo].[PESSOATELEFONE] CHECK CONSTRAINT [FK_PESTEL_CODIGO_PESSOA]
GO
/****** Object:  ForeignKey [FK_RACA_CODIGO_ESPECIE]    Script Date: 11/24/2011 20:54:16 ******/
ALTER TABLE [dbo].[RACA]  WITH CHECK ADD  CONSTRAINT [FK_RACA_CODIGO_ESPECIE] FOREIGN KEY([CODIGO_ESPECIE])
REFERENCES [dbo].[ESPECIE] ([CODIGO])
GO
ALTER TABLE [dbo].[RACA] CHECK CONSTRAINT [FK_RACA_CODIGO_ESPECIE]
GO
/****** Object:  ForeignKey [FK_USU_CODIGO_PESSOA]    Script Date: 11/24/2011 20:54:16 ******/
ALTER TABLE [dbo].[USUARIO]  WITH CHECK ADD  CONSTRAINT [FK_USU_CODIGO_PESSOA] FOREIGN KEY([CODIGO_PESSOA])
REFERENCES [dbo].[PESSOA] ([CODIGO])
GO
ALTER TABLE [dbo].[USUARIO] CHECK CONSTRAINT [FK_USU_CODIGO_PESSOA]
GO
/****** Object:  ForeignKey [FK_USUARIO_CODIGO_PERFIL]    Script Date: 11/24/2011 20:54:16 ******/
ALTER TABLE [dbo].[USUARIO]  WITH CHECK ADD  CONSTRAINT [FK_USUARIO_CODIGO_PERFIL] FOREIGN KEY([CODIGO_PERFIL])
REFERENCES [dbo].[PERFIL] ([CODIGO])
GO
ALTER TABLE [dbo].[USUARIO] CHECK CONSTRAINT [FK_USUARIO_CODIGO_PERFIL]
GO
/****** Object:  ForeignKey [FK__VETERINAR__CODIG__1F98B2C1]    Script Date: 11/24/2011 20:54:16 ******/
ALTER TABLE [dbo].[VETERINARIO]  WITH CHECK ADD FOREIGN KEY([CODIGO_PESSOA])
REFERENCES [dbo].[PESSOA] ([CODIGO])
GO
